### ISSUE TITLE
Git workflow; branches, documentation, oh my!

### ISSUE THREAD

**Issue by lillian-lemmer** [hypatia-software-organization/hypatia-engine#120]
After talking to @ejmr, I've decided I want to change our git workflow (just a bit!).

This is going to require combing over and changing `CONTRIBUTING.md`. Which, therein, we should have "the process of a pull request" and it shows creating a fork, cloning the fork, branching from master, making edits, commit, pull review against master, if approved merge to `next`, once release is ready merge to `master` with `git checkout master; git merge --ff-only next` and tag with `git tag -s 0.4.0`. or the like.

@ejmr will be posting herein notes and they're the authority on this subject.

**Comment by lillian-lemmer** [comment]
@ejmr 8a7970 is amazing, thank you so much! You have my :+1: :+1:

**Comment by ejmr** [comment]
Somebody please double-check 8afb1ee2375dc2e7c36adeeb79adadb848c4c9e1 for typos or if any tips need further explanation before merging.

**Comment by ejmr** [comment]
Forcibly changed the commit, which is now cca0364fb493cafafcdcec676f208ed6ec1e2865.  Somebody please review it for typos and clarity.
