### ISSUE TITLE
Test script should reinstall pip depends

### ISSUE THREAD

**Issue by lillian-lemmer** [hypatia-software-organization/hypatia-engine#97]

**Comment by ejmr** [comment]
```sh
"$PIP" install --user --no-cache-dir --upgrade .
```

You mean like that?  If so, maybe the script should also remove dependencies when running `uninstall`, which I don't think it does by default.  Removing dependencies as part of the process would remove any dependencies which we later decide to stop using.

**Comment by lillian-lemmer** [comment]
I think there's a `--force-reinstall`

**Comment by ejmr** [comment]
> I think there's a `--force-reinstall`

There is; I just tried it out.  PIP still requires `--upgrade`, otherwise `--force-reinstall` does nothing.

**Comment by ejmr** [comment]
You were asking me about the "tags" like `[Chore]`, they come from [my Git commit template](http://ericjmritz.name/2015/05/27/my-global-git-commit-template/).  I find having a commit template useful for having stuff like `GitHub-Issue:` or `Closes:` lines already in every commit message, so I can just un-comment the metadata I want to use.
